spring:
    application:
        name: auth
    datasource:
        url: jdbc:mysql://localhost:3306/user
        username: root
        password: fuckDruid1!

security:
    jwt:
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        expiration-time: 3_600_000

server:
    port: 3000

logging:
    level:
        web: DEBUG
        org:
            springframework:
                security: debug
