spring:
    application:
        name: auth
    datasource:
        url: jdbc:mysql://localhost:3306/user
        username: root
        password: fuckDruid1!
    profies:
        include: jwt

server:
    port: 3000

logging:
    level:
        org:
            springframework:
                security: TRACE
